baseurl = "https://lexi.flvr.top/blog/"
languageCode = "en-us"
theme = "terminal"
paginate = 42

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = false

[taxonomies]
  tag = "tags"

[languages]
  [languages.en]
    title = "Alexander Pavlenko"
    subtitle = "Blog"
    keywords = "devops, security, programming, music, rationality, personal"
    copyright = '<div style="font-size:0.5rem"><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Blog</span> by <a xmlns:cc="https://creativecommons.org/ns#" href="https://lexi.flvr.top/" property="cc:attributionName" rel="cc:attributionURL">Alexander Pavlenko</a> is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a></div>'
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "☰"
      logoHomeLink = "/blog/"

    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"
#      [[languages.en.menu.main]]
#        identifier = "showcase"
#        name = "Showcase"
#        url = "/showcase"
